version: "3.8"

services:
  agas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agas
    command: ["agas"]
    tty: true
    stdin_open: true
    environment:
      - LICENSE=MIT
