version: '3.8' #
services:
  agas:
    build:
      context: .
      dockerfile: Dockerfile
    image: mmdy/agas:latest
    container_name: agas_cli
    entrypoint: ['agas']
    command: ['--help']
    tty: true
    stdin_open: true
    environment:
      - BUN_INSTALL=/usr/local/bin/bun
    volumes:
      - .:/app:ro
