export enum RequestMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
  ALL = 'ALL',
  OPTIONS = 'OPTIONS',
  HEAD = 'HEAD',
  SEARCH = 'SEARCH',
  PROPFIND = 'PROPFIND',
  PROPPATCH = 'PROPPATCH',
  MKCOL = 'MKCOL',
  COPY = 'COPY',
  MOVE = 'MOVE',
  LOCK = 'LOCK',
  UNLOCK = 'UNLOCK',
}
